apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: webmaster@change_domain
    privateKeySecretRef:
      name: le-staging-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector: {}
      dns01:
        webhook:
          groupName: acme.infomaniak.com
          solverName: infomaniak
          config:
            apiTokenSecretRef:
              name: infomaniak-api-credentials
              key: api-token
